
if data.raw["item"]["alien-blue-alloy"] then
	data:extend({
 {
    type = "item-group",
    hidden = false,
    name = "AlchemyBoBPlates",
    icon = "__Alchemy__/graphics/icons/alchemy.png",
    inventory_order = "f",
    order = "f"
  },
    {
    type = "item-subgroup",
    name = "AlchemyPB",
    group = "AlchemyBoBPlates",
    order = "p",
  },

 { type = "recipe", name = "alchemy-gold-to-alien-blue-alloy",                 subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "alien-blue-alloy" },
 { type = "recipe", name = "alchemy-gold-to-alien-orange-alloy",               subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "alien-orange-alloy" },
 { type = "recipe", name = "alchemy-gold-to-alien-acid",                       subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="alien-acid", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-alien-explosive",                  subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="alien-explosive", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-alien-poison",                     subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="alien-poison", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-alien-fire",                       subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="alien-fire", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-bronze-alloy",                     subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "bronze-alloy" },
 { type = "recipe", name = "alchemy-gold-to-brass-alloy",                      subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "brass-alloy" },
 { type = "recipe", name = "alchemy-gold-to-electrum-alloy",                   subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "electrum-alloy" },
 { type = "recipe", name = "alchemy-gold-to-copper-tungsten-alloy",            subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "copper-tungsten-alloy" },
 { type = "recipe", name = "alchemy-gold-to-tungsten-carbide",                 subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "tungsten-carbide" },
 { type = "recipe", name = "alchemy-gold-to-gunmetal-alloy",                   subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "gunmetal-alloy" },
 { type = "recipe", name = "alchemy-gold-to-invar-alloy",                      subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "invar-alloy" },
 { type = "recipe", name = "alchemy-gold-to-nitinol-alloy",                    subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "nitinol-alloy" },
 { type = "recipe", name = "alchemy-gold-to-cobalt-steel-alloy",               subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "cobalt-steel-alloy" },
 { type = "recipe", name = "alchemy-gold-to-liquid-air",                       subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="liquid-air", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-lithia-water",                     subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="lithia-water", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-hydrogen",                         subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="hydrogen", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-oxygen",                           subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="oxygen", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-nitrogen",                         subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="nitrogen", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-chlorine",                         subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="chlorine", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-hydrogen-chloride",                subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="hydrogen-chloride", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-nitrogen-dioxide",                 subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="nitrogen-dioxide", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-sulfur-dioxide",                   subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="sulfur-dioxide", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-nitric-acid",                      subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="nitric-acid", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-tungstic-acid",                    subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="tungstic-acid", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-ferric-chloride-solution",         subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="ferric-chloride-solution", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-liquid-fuel",                      subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20},{type="fluid", name="water", amount=20}}, results={{type="fluid", name="liquid-fuel", amount=20}} },
 { type = "recipe", name = "alchemy-gold-to-salt",                             subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "salt" },
 { type = "recipe", name = "alchemy-gold-to-lithium-chloride",                 subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "lithium-chloride" },
 { type = "recipe", name = "alchemy-gold-to-lithium-perchlorate",              subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "lithium-perchlorate" },
 { type = "recipe", name = "alchemy-gold-to-sodium-hydroxide",                 subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "sodium-hydroxide" },
 { type = "recipe", name = "alchemy-gold-to-calcium-chloride",                 subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "calcium-chloride" },
 { type = "recipe", name = "alchemy-gold-to-lead-oxide",                       subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "lead-oxide" },
 { type = "recipe", name = "alchemy-gold-to-alumina",                          subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "alumina" },
 { type = "recipe", name = "alchemy-gold-to-tungsten-oxide",                   subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "tungsten-oxide" },
 { type = "recipe", name = "alchemy-gold-to-powdered-tungsten",                subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "powdered-tungsten" },
 { type = "recipe", name = "alchemy-gold-to-silicon-powder",                   subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "silicon-powder" },
 { type = "recipe", name = "alchemy-gold-to-silicon-nitride",                  subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "silicon-nitride" },
 { type = "recipe", name = "alchemy-gold-to-cobalt-oxide",                     subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "cobalt-oxide" },
 { type = "recipe", name = "alchemy-gold-to-silicon-carbide",                  subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "silicon-carbide" },
 { type = "recipe", name = "alchemy-gold-to-silver-nitrate",                   subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "silver-nitrate" },
 { type = "recipe", name = "alchemy-gold-to-silver-oxide",                     subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "silver-oxide" },
 { type = "recipe", name = "alchemy-gold-to-advanced-processing-unit",         subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "advanced-processing-unit" },
 { type = "recipe", name = "alchemy-gold-to-gem-ore",                          subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "gem-ore" },
 { type = "recipe", name = "alchemy-gold-to-ruby-ore",                         subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "ruby-ore" },
 { type = "recipe", name = "alchemy-gold-to-sapphire-ore",                     subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "sapphire-ore" },
 { type = "recipe", name = "alchemy-gold-to-emerald-ore",                      subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "emerald-ore" },
 { type = "recipe", name = "alchemy-gold-to-amethyst-ore",                     subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "amethyst-ore" },
 { type = "recipe", name = "alchemy-gold-to-topaz-ore",                        subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "topaz-ore" },
 { type = "recipe", name = "alchemy-gold-to-diamond-ore",                      subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "diamond-ore" },
 { type = "recipe", name = "alchemy-gold-to-gold-ore",                         subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "gold-ore" },
 { type = "recipe", name = "alchemy-gold-to-lead-ore",                         subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "lead-ore" },
 { type = "recipe", name = "alchemy-gold-to-silver-ore",                       subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "silver-ore" },
 { type = "recipe", name = "alchemy-gold-to-tin-ore",                          subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "tin-ore" },
 { type = "recipe", name = "alchemy-gold-to-tungsten-ore",                     subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "tungsten-ore" },
 { type = "recipe", name = "alchemy-gold-to-zinc-ore",                         subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "zinc-ore" },
 { type = "recipe", name = "alchemy-gold-to-bauxite-ore",                      subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "bauxite-ore" },
 { type = "recipe", name = "alchemy-gold-to-rutile-ore",                       subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "rutile-ore" },
 { type = "recipe", name = "alchemy-gold-to-quartz",                           subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "quartz" },
 { type = "recipe", name = "alchemy-gold-to-nickel-ore",                       subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "nickel-ore" },
 { type = "recipe", name = "alchemy-gold-to-cobalt-ore",                       subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "cobalt-ore" },
 { type = "recipe", name = "alchemy-gold-to-steel-gear-wheel",                 subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "steel-gear-wheel" },
 { type = "recipe", name = "alchemy-gold-to-steel-bearing-ball",               subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "steel-bearing-ball" },
 { type = "recipe", name = "alchemy-gold-to-steel-bearing",                    subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "steel-bearing" },
 { type = "recipe", name = "alchemy-gold-to-brass-gear-wheel",                 subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "brass-gear-wheel" },
 { type = "recipe", name = "alchemy-gold-to-titanium-gear-wheel",              subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "titanium-gear-wheel" },
 { type = "recipe", name = "alchemy-gold-to-titanium-bearing-ball",            subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "titanium-bearing-ball" },
 { type = "recipe", name = "alchemy-gold-to-titanium-bearing",                 subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "titanium-bearing" },
 { type = "recipe", name = "alchemy-gold-to-tungsten-gear-wheel",              subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "tungsten-gear-wheel" },
 { type = "recipe", name = "alchemy-gold-to-nitinol-gear-wheel",               subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "nitinol-gear-wheel" },
 { type = "recipe", name = "alchemy-gold-to-nitinol-bearing-ball",             subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "nitinol-bearing-ball" },
 { type = "recipe", name = "alchemy-gold-to-nitinol-bearing",                  subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "nitinol-bearing" },
 { type = "recipe", name = "alchemy-gold-to-ceramic-bearing-ball",             subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "ceramic-bearing-ball" },
 { type = "recipe", name = "alchemy-gold-to-ceramic-bearing",                  subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "ceramic-bearing" },
 { type = "recipe", name = "alchemy-gold-to-lithium-ion-battery",              subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "lithium-ion-battery" },
 { type = "recipe", name = "alchemy-gold-to-silver-zinc-battery",              subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "silver-zinc-battery" },
 { type = "recipe", name = "alchemy-gold-to-grinding-wheel",                   subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "grinding-wheel" },
 { type = "recipe", name = "alchemy-gold-to-polishing-wheel",                  subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "polishing-wheel" },
 { type = "recipe", name = "alchemy-gold-to-tin-plate",                        subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "tin-plate" },
 { type = "recipe", name = "alchemy-gold-to-silver-plate",                     subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "silver-plate" },
 { type = "recipe", name = "alchemy-gold-to-lead-plate",                       subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "lead-plate" },
 { type = "recipe", name = "alchemy-gold-to-gold-plate",                       subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "gold-plate" },
 { type = "recipe", name = "alchemy-gold-to-nickel-plate",                     subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "nickel-plate" },
 { type = "recipe", name = "alchemy-gold-to-zinc-plate",                       subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "zinc-plate" },
 { type = "recipe", name = "alchemy-gold-to-aluminium-plate",                  subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "aluminium-plate" },
 { type = "recipe", name = "alchemy-gold-to-titanium-plate",                   subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "titanium-plate" },
 { type = "recipe", name = "alchemy-gold-to-tungsten-plate",                   subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "tungsten-plate" },
 { type = "recipe", name = "alchemy-gold-to-silicon",                          subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "silicon" },
 { type = "recipe", name = "alchemy-gold-to-lithium",                          subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "lithium" },
 { type = "recipe", name = "alchemy-gold-to-cobalt-plate",                     subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "cobalt-plate" },
 { type = "recipe", name = "alchemy-gold-to-carbon",                           subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "carbon" },
 { type = "recipe", name = "alchemy-gold-to-resin",                            subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "resin" },
 { type = "recipe", name = "alchemy-gold-to-rubber",                           subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "rubber" },
 { type = "recipe", name = "alchemy-gold-to-glass",                            subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "glass" },
 { type = "recipe", name = "alchemy-gold-to-silicon-wafer",                    subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "silicon-wafer" },
 { type = "recipe", name = "alchemy-gold-to-lithium-cobalt-oxide",             subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "lithium-cobalt-oxide" },
 { type = "recipe", name = "alchemy-gold-to-synthetic-wood",                   subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "synthetic-wood" },
 { type = "recipe", name = "alchemy-gold-to-polishing-compound",               subgroup = "AlchemyPB", category = "chemistry", enabled = "false", energy_required = 2, ingredients ={{"alchemy-gold",20}}, result = "polishing-compound" }

,

{ 	type = "technology", 	name = "alchemy-bobs-plates", 	icon = "__Alchemy__/graphics/icons/alchemy.png", 	prerequisites = {"alchemy-basic-ores"}, 	unit = 	{ 	count = 100, 	ingredients = { {"science-pack-1", 1},{"science-pack-2", 1}, }, 	time = 60 	}, 	effects = { 		

{type = "unlock-recipe",recipe = "alchemy-gold-to-alien-blue-alloy"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-alien-orange-alloy"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-alien-acid"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-alien-explosive"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-alien-poison"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-alien-fire"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-bronze-alloy"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-brass-alloy"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-electrum-alloy"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-copper-tungsten-alloy"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-tungsten-carbide"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-gunmetal-alloy"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-invar-alloy"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-nitinol-alloy"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-cobalt-steel-alloy"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-liquid-air"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-lithia-water"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-hydrogen"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-oxygen"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-nitrogen"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-chlorine"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-hydrogen-chloride"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-nitrogen-dioxide"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-sulfur-dioxide"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-nitric-acid"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-tungstic-acid"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-ferric-chloride-solution"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-liquid-fuel"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-salt"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-lithium-chloride"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-lithium-perchlorate"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-sodium-hydroxide"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-calcium-chloride"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-lead-oxide"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-alumina"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-tungsten-oxide"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-powdered-tungsten"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-silicon-powder"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-silicon-nitride"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-cobalt-oxide"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-silicon-carbide"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-silver-nitrate"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-silver-oxide"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-advanced-processing-unit"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-gem-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-ruby-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-sapphire-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-emerald-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-amethyst-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-topaz-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-diamond-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-gold-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-lead-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-silver-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-tin-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-tungsten-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-zinc-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-bauxite-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-rutile-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-quartz"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-nickel-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-cobalt-ore"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-steel-gear-wheel"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-steel-bearing-ball"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-steel-bearing"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-brass-gear-wheel"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-titanium-gear-wheel"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-titanium-bearing-ball"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-titanium-bearing"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-tungsten-gear-wheel"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-nitinol-gear-wheel"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-nitinol-bearing-ball"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-nitinol-bearing"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-ceramic-bearing-ball"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-ceramic-bearing"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-lithium-ion-battery"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-silver-zinc-battery"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-grinding-wheel"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-polishing-wheel"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-tin-plate"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-silver-plate"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-lead-plate"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-gold-plate"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-nickel-plate"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-zinc-plate"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-aluminium-plate"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-titanium-plate"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-tungsten-plate"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-silicon"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-lithium"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-cobalt-plate"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-carbon"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-resin"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-rubber"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-glass"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-silicon-wafer"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-lithium-cobalt-oxide"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-synthetic-wood"},
{type = "unlock-recipe",recipe = "alchemy-gold-to-polishing-compound"}

 	}, 	upgrade = true, 	order = "e-n-f" 	} 	


})
end